[package]
name = "locknest"
version = "0.1.0"
authors = ["serprex"]

[dependencies]
iron = "0.5"
router = "0.5"
urlencoded = "0.5"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

csv = "1.0.0-beta.3"
lazy_static = "0.2"
levenshtein = "1.0"
suffix = "1.0"
